# -*- coding: utf-8 -*-
"""
/***************************************************************************
 parcelplotter
                                 A QGIS plugin
 Plotting polygons based on ordered codes.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-07-10
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Nuwe Surv
        email                : nuwesurv@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
# Import the code for the dialog
from .module_ui.parcelplotter_dialog import ParcelPlotterDialog
from qgis.core import QgsProject, QgsVectorLayer, QgsField
import os.path
import pandas as pd
import geopandas as gpd
import shapely as sh


class parcelplotter:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'parcelplotter_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&parcelplotter')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('parcelplotter', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(
                    os.path.dirname(__file__), "icon.png"
                )
                
        # icon_path = ':/plugins/parcelplotter/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'parcelplotter'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&parcelplotter'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ParcelPlotterDialog()
            self.dlg.runbutton.clicked.connect(self.plot_parcels)
            self.dlg.closebutton.clicked.connect(self.dlg.close)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()


    
    def plot_parcels(self):
        """Plot parcels using user-selected columns"""
        filepath = self.dlg.filepath_store.text()
        if not os.path.exists(filepath) or filepath == "No file selected":
            self.dlg.response.setText("File does not exist")
            return

        # Get selected column names
        eastings = self.dlg.eastings.currentText()
        northings = self.dlg.northings.currentText()
        code = self.dlg.code.currentText()

        if not all([eastings, northings, code]):
            self.dlg.response.setText("Please select all columns")
            return

        try:
            # Read file
            if filepath.endswith('.csv'):
                df = pd.read_csv(filepath)
            elif filepath.endswith('.xlsx'):
                df = pd.read_excel(filepath)

            # Validate columns
            if not all(col in df.columns for col in [eastings, northings, code]):
                self.dlg.response.setText("Selected columns not found in file")
                return

            # Validate numeric columns
            if not pd.api.types.is_numeric_dtype(df[eastings]) or not pd.api.types.is_numeric_dtype(df[northings]):
                self.dlg.response.setText("Eastings and Northings must be numeric")
                return

            # Create geometry
            df['geometry'] = df.index.map(lambda i: sh.Point([df.loc[i, eastings], df.loc[i, northings]]))

            gdf = gpd.GeoDataFrame(data=df)

            unique_codes = gdf[code].unique()
            new_gdf = gpd.GeoDataFrame(columns=[code, 'geometry'])
            for i, unique_code in enumerate(unique_codes):
                gdf1 = gdf[gdf[code] == unique_code]
                parcel_boundary = []
                for point in gdf1['geometry']:
                    parcel_boundary.append([point.x, point.y])
                try:
                    new_gdf.loc[i, code] = unique_code
                    new_gdf.loc[i, 'geometry'] = sh.Polygon(parcel_boundary)
                except Exception as e:
                    self.dlg.response.setText(f"Error creating polygon for code {unique_code}: {str(e)}")
                    continue

            if new_gdf.empty:
                self.dlg.response.setText("No valid polygons created")
                return

            new_gdf = new_gdf.set_crs(epsg=32636)
            new_layer_path = os.path.splitext(filepath)[0] + '_2.gpkg'
            new_gdf.to_file(new_layer_path, driver='GPKG')

            # Load layer in QGIS
            layer_name = 'Plotted Parcels'
            layer = QgsVectorLayer(new_layer_path, layer_name, 'ogr')

            if not layer.isValid():
                self.dlg.response.setText("Layer failed to load")
                return

            QgsProject.instance().addMapLayer(layer)
            self.dlg.response.setText("Parcels plotted successfully")

        except Exception as e:
            self.dlg.response.setText(f"Error: {str(e)}")
