# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Nuwe Surv\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ugsurv\Ugsurv_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UgsurvDialogBase(object):
    def setupUi(self, UgsurvDialogBase):
        UgsurvDialogBase.setObjectName("UgsurvDialogBase")
        UgsurvDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(UgsurvDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")

        self.retranslateUi(UgsurvDialogBase)
        self.button_box.accepted.connect(UgsurvDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(UgsurvDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UgsurvDialogBase)

    def retranslateUi(self, UgsurvDialogBase):
        _translate = QtCore.QCoreApplication.translate
        UgsurvDialogBase.setWindowTitle(_translate("UgsurvDialogBase", "Ugsurv"))
