# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Ugsurv
                                 A QGIS plugin
 General purpose CAD like plugin for Ug survey works
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-20
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Nuwe Surv
        email                : nuwesurv@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon, QFont, QColor
from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtCore import Qt
from qgis.core import (
    QgsVectorLayer,
    QgsProject,
    QgsFeature,
    QgsGeometry,
    QgsPointXY,
    QgsField,
    QgsWkbTypes,
    QgsLineSymbol,
    QgsPalLayerSettings, 
    QgsTextFormat, 
    QgsVectorLayerSimpleLabeling,
    QgsProject,
    QgsSnappingConfig
)
from PyQt5.QtCore import QVariant
from qgis.gui import QgsRubberBand, QgsVertexMarker
from PyQt5.QtWidgets import QShortcut
from PyQt5.QtGui import QKeySequence
from qgis.gui import QgsMapCanvas



# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .modules.terminal import TerminalDialog
from .Ugsurv_dialog import UgsurvDialog
from .modules.module_ui.parcelplotter_dialog import ParcelPlotterDialog
from .modules.module_ui.import_print import ImportPrintDialog
import os.path
from .modules.keymap import KeyPressFilter
import math
from .modules.dimension_drawer import DimensionDrawer
from .modules.game1 import Game1
from .modules.snapSettingConfig import snapSettingConfig
from .modules.topology_solver import TopologySolver
from .modules.circle_drawer import CircleDrawer
from .modules.GlobalKeyPressFilter import GlobalKeyPressFilter


class Ugsurv:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Ugsurv_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Ugsurv')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        
        
        # ====================================================================================
        # plugin intanstisions
        self.canvas = self.iface.mapCanvas()
        self.command_list = ['pp', 'dim', 'adim', 'circle', 'ts'] # was created for suggection purposes.
        ...
        self.active = False  # Track plugin toggle state
        ...
        
        # ====================================================================================
        
        
        

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Ugsurv', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)
        self.actions.append(action)
        
        action.setCheckable(True)  # <-- Make it toggleable
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(self.plugin_dir, "icon.png")
        self.add_action(
            icon_path,
            text=self.tr(u'Ugsurv'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        # Removes the plugin icon from the Tool bar.
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&ParcelPro'),
                action)
            self.iface.removeToolBarIcon(action)
        # Removes the plugin from the docks.
        if hasattr(self, "terminal_dock") and self.terminal_dock:
            self.iface.removeDockWidget(self.terminal_dock)
            self.terminal_dock.deleteLater()
            self.terminal_dock = None
        
        # Remove all tools
        self.destroyAllTools()


    def run(self):
        """Run method that performs all the real work"""
        if self.active:
            # Plugin is already active → deactivate
            self.destroyAllTools()  # deactivate map tools
            if hasattr(self, "terminal_dock") and self.terminal_dock:
                self.iface.removeDockWidget(self.terminal_dock)
                self.terminal_dock.deleteLater()
                self.terminal_dock = None
            
            self.active = False
            return  # Exit early
        
        # If we get here → plugin is inactive → activate it
        self.active = True
        
        # 🔥 remove old dock if it already exists (important for reloads)
        if hasattr(self, "terminal_dock") and self.terminal_dock:
            try:
                self.iface.removeDockWidget(self.terminal_dock)
                self.terminal_dock.deleteLater()
            except:
                pass
            self.terminal_dock = None

        # terminal dock
        self.terminal_dock = TerminalDialog(self.iface.mainWindow())
        self.iface.addDockWidget(Qt.BottomDockWidgetArea, self.terminal_dock)
        self.terminal_dock.command.setFocus()
        
        # Connect these functions to ui
        self.terminal_dock.command.returnPressed.connect(self.acceptInput)
        
        # This will help to setup the required snap settings.
        snapSettingConfig()
        
        # # Install global key filter so any key goes to terminal
        # self.key_filter = GlobalKeyPressFilter(self.terminal_dock)
        # self.iface.mainWindow().installEventFilter(self.key_filter)
    
    
    def acceptInput(self):
        # update the history index and the commandHistory
        self.terminal_dock.commandHistory.insert(-1,self.terminal_dock.command.text())
        self.terminal_dock.historyIndex = len(self.terminal_dock.commandHistory) - 1
        
        self.prevCommand = self.terminal_dock.command.text()
        self.terminal_dock.commandOutputText += f'\n>>> {self.terminal_dock.command.text()}'
        self.terminal_dock.command.setText('')
        
        try:
            if self.prevCommand.lower() != 'help':
                answer = eval(self.prevCommand)
                self.terminal_dock.commandOutputText += f' = {answer}'
        except Exception as e:
            # print(f"{self.prevCommand} can't be evaluated")
            ...
        
        # first update the input command i the display
        self.terminal_dock.commandDisplay.setText(self.terminal_dock.commandOutputText)
        
        # =================================================================================================
        # then caryyout operations.
        # our first command is tracking the cursor cordinates.
        # Fifth command is for adding dimesnions to entire geometries selected
        if self.prevCommand.lower() == 'help':
            self.terminal_dock.commandOutputText += "\nCommands:"
            self.terminal_dock.commandOutputText += "\ndim - add Dimesion on segment or between two points."
            self.terminal_dock.commandOutputText += "\nadim - add Dimensions on entire feature selected"
            self.terminal_dock.commandOutputText += "\nts - topologysolver"
            self.terminal_dock.commandOutputText += "\nplot - parcelploter"
            self.terminal_dock.commandOutputText += "\ngame - Starts GIS game"
            self.terminal_dock.commandOutputText += "\nc - topologysolver"
            self.terminal_dock.commandOutputText += "\nimport - topologysolver"
            self.terminal_dock.commandDisplay.setText(self.terminal_dock.commandOutputText)
            
        # Command is for clearing the terminal.
        if self.prevCommand == 'cls':
            self.terminal_dock.commandHistory = ['']
            self.terminal_dock.historyIndex = 0
            self.terminal_dock.commandOutputText = 'Loading plugin...\nPlugin has been loaded 🧪...\nTerminal cleared...'
            self.terminal_dock.commandDisplay.setText(self.terminal_dock.commandOutputText)
            
        # Command is for automatic plotting of parcels.
        if self.prevCommand == 'pp':
            self.dlg = ParcelPlotterDialog()
            # self.dlg = ParcelPlotterDialog(parent=self.iface.mainWindow())  # if you want the dialog to not appear like a separate qgis windo but instead witin the same qgis interface window.
            self.dlg.show()
            
        # Command is for adding dimesnions to entire geometries selected
        if self.prevCommand.lower() == 'import':
            self.dlg = ImportPrintDialog(terminal_dock=self.terminal_dock)
            self.dlg.show()
            
        # Command is for playing QGIS game.
        if self.prevCommand.lower() == 'game':
            self.map_tool = Game1(self.canvas, self.terminal_dock, 'single')
            self.canvas.setMapTool(self.map_tool)
            
        # Command is for adding dimesnions.
        if self.prevCommand.lower() == 'dim':
            self.map_tool = DimensionDrawer(self.canvas, self.terminal_dock, 'single')
            self.canvas.setMapTool(self.map_tool)
            
        # Command is for adding dimesnions to entire geometries selected
        if self.prevCommand.lower() == 'adim':
            self.map_tool = DimensionDrawer(self.canvas, self.terminal_dock, 'selected')
            self.canvas.setMapTool(self.map_tool)
            
        # Command is for adding dimesnions to entire geometries selected
        if self.prevCommand.lower() == 'ts':
            self.map_tool = TopologySolver(self.canvas, self.terminal_dock)
            self.canvas.setMapTool(self.map_tool)
            
        # The function we have here below is for drawing a circle at the cursor cords
        if self.prevCommand == 'c':
            # step1: get the center where cordinates shall be placed.
            self.map_tool = CircleDrawer(self.canvas, self.terminal_dock)
            self.canvas.setMapTool(self.map_tool)
            
            
            
            
            
            
            
            
    def destroyAllTools(self):
        try:
            self.map_tool.deactivate()
        except:
            pass
            
        try:
            self.dlg.close()
            self.dlg.deleteLater()
            self.dlg = None
        except:
            pass
            
            
            
            