# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UgsurvDialog
                                 A QGIS plugin
 General purpose CAD like plugin for Ug survey works
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-20
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Nuwe Surv
        email                : nuwesurv@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
