# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Ugsurv
                                 A QGIS plugin
 General purpose CAD like plugin for Ug survey works
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-20
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Nuwe Surv
        email                : nuwesurv@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import contextlib

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon, QFont, QColor, QPixmap, QPainter, QPen
from qgis.PyQt.QtWidgets import QAction, QApplication, QToolButton, QMenu
from qgis.PyQt.QtCore import Qt, QRect
from qgis.core import (
    QgsVectorLayer,
    QgsProject,
    QgsFeature,
    QgsGeometry,
    QgsPointXY,
    QgsField,
    QgsWkbTypes,
    QgsLineSymbol,
    QgsPalLayerSettings,
    QgsTextFormat,
    QgsVectorLayerSimpleLabeling,
    QgsSnappingConfig
)
from qgis.PyQt.QtCore import QVariant
from qgis.gui import QgsRubberBand, QgsVertexMarker
from qgis.PyQt.QtWidgets import QShortcut
from qgis.PyQt.QtGui import QKeySequence
from qgis.gui import QgsMapCanvas



# Initialize Qt resources from file resources.py
from .resources import *  # noqa: F403
# Import the code for the dialog
from .modules.terminal import TerminalDialog

import os.path
from .modules.key_filter import KeyPressFilter
import math
from .modules.dimension_drawer import DimensionDrawer
from .modules.laser_game import Game1
from .modules.snap_utils import init_snap
from .modules.topology_solver import TopologySolver
from .modules.fix_geometry import FixGeometry
from .module_wz_dialogs.parcel_plotter import ParcelPlotterDialog
from .module_wz_dialogs.layout_importer import ImportPrintDialog
from .module_wz_dialogs.file_importer import FileImportDialog
from .module_wz_dialogs.append_geometry import GeometryAppenderDock
from .module_wz_dialogs.crs_adjust import CrsAdjustDock
from .module_wz_dialogs.solve_topology_issues import SolveTopologyDock
from .module_wz_dialogs.spiky_geometry import SpikyGeomsDock
from .module_wz_dialogs.overlap_points import OverlapPointsDock
from .module_wz_dialogs.revert_geometry import RevertMapTool
from .module_wz_dialogs.feature_navigator import FeatureNavigatorDock
from .modules.circle_drawer import CircleDrawer
from .modules.polyline_drawer import PolylineDrawer
from .modules.vertex_selector import VertexSelector
from .modules.properties_panel import PropertiesDock
from .maptool import UgsurvMaptool
from .modules.trim_tool import TrimTool
from .modules.extend_tool import ExtendTool
from .modules.move_tool import MoveTool
from .modules.copy_tool import CopyTool
from .modules.offset_tool import OffsetTool
from .modules.rotate_tool import RotateTool
from .modules.scale_tool import ScaleTool
from .modules.join_tool import JoinTool
from .modules.break_tool import BreakTool
from .modules.chamfer_tool import ChamferTool
from .modules.explode_tool import ExplodeTool
from .modules.hatch_tool import HatchTool
from .modules.point_drawer import PointDrawer
from .modules import snap_manager
from .modules.layer_utils import restore_no_legend_layers
import ast


class Ugsurv:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Ugsurv_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Ugsurv')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        
      
        

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Ugsurv', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)
        self.actions.append(action)
        
        action.setCheckable(True)  # <-- Make it toggleable
        return action


    def activate_maptool(self):
        """Re-activate the UgSurv map tool (e.g. after using a QGIS built-in tool)."""
        if not self.active or not hasattr(self, 'global_map_tool') or not self.global_map_tool:
            return
        self.canvas.setMapTool(self.global_map_tool)

    def _toggle_maptool(self):
        """Cursor-icon button: activate plugin if off, else toggle the maptool on/off."""
        if not self.active:
            self.run()
            return
        current = self.canvas.mapTool()
        if current is self.global_map_tool:
            self.canvas.unsetMapTool(self.global_map_tool)
        else:
            self.canvas.setMapTool(self.global_map_tool)

    def _on_map_tool_set(self, new_tool, _old_tool):
        """Keep the toolbar button checked iff our tool owns the canvas."""
        if hasattr(self, '_maptool_action'):
            self._maptool_action.setChecked(
                new_tool is self.global_map_tool
            )

    def _on_plugin_button(self):
        """Cursor-icon toolbar button: activate plugin if off, re-activate maptool if on."""
        if not self.active:
            self.run()
        else:
            self.activate_maptool()

    def _on_terminal_visibility(self, visible):
        """Deactivate the plugin when the terminal dock is hidden (backup path)."""
        if not visible and self.active:
            with contextlib.suppress(Exception):
                self.terminal_dock.visibilityChanged.disconnect(self._on_terminal_visibility)
            self.run()

    def _on_terminal_closed(self):
        """Deactivate the plugin when the terminal X button is clicked (primary path)."""
        if not self.active:
            return
        with contextlib.suppress(Exception):
            self.terminal_dock.visibilityChanged.disconnect(self._on_terminal_visibility)
        self.run()

    # ------------------------------------------------------------------ snap
    @staticmethod
    def _make_snap_icon(active=True):
        """Draw a U-magnet icon; grey when all snap modes are off."""
        size = 24
        px = QPixmap(size, size)
        px.fill(Qt.GlobalColor.transparent)
        p = QPainter(px)
        p.setRenderHint(QPainter.RenderHint.Antialiasing)

        arm_col = QColor(240, 165, 0) if active else QColor(130, 130, 130)
        p.setPen(QPen(arm_col, 3, Qt.PenStyle.SolidLine, Qt.PenCapStyle.RoundCap))
        p.drawLine(7, 4, 7, 14)
        p.drawLine(17, 4, 17, 14)
        p.drawArc(QRect(7, 9, 10, 10), 0, -180 * 16)

        lc = QColor(210, 50, 50)  if active else QColor(130, 130, 130)
        rc = QColor(50, 80, 210)  if active else QColor(130, 130, 130)
        p.setPen(QPen(lc, 3, Qt.PenStyle.SolidLine, Qt.PenCapStyle.SquareCap))
        p.drawLine(4, 4, 10, 4)
        p.setPen(QPen(rc, 3, Qt.PenStyle.SolidLine, Qt.PenCapStyle.SquareCap))
        p.drawLine(14, 4, 20, 4)
        p.end()
        return QIcon(px)

    
    def _on_snap_toggle(self, key, checked):
        snap_manager.set_enabled(key, checked)
        any_on = any(a.isChecked() for a in self._snap_actions.values())
        self._snap_btn.setIcon(self._make_snap_icon(any_on))

    def _set_all_snaps(self, state):
        for act in self._snap_actions.values():
            act.setChecked(state)   # triggers _on_snap_toggle via toggled signal

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(self.plugin_dir, "icon.png")
        self.add_action(
            icon_path,
            text=self.tr(u'Ugsurv'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # Second button: restore the UgSurv map tool cursor after switching to a QGIS tool
        self._maptool_action = QAction(
            self._maptool_icon(),
            self.tr(u'Activate UgSurv Map Tool'),
            self.iface.mainWindow()
        )
        self._maptool_action.setToolTip('Activate UgSurv map tool')
        self._maptool_action.setCheckable(True)
        self._maptool_action.setChecked(False)
        self._maptool_action.triggered.connect(self._toggle_maptool)
        self.iface.addToolBarIcon(self._maptool_action)
        self.actions.append(self._maptool_action)

        # Snap options dropdown (magnet button)
        self._snap_btn = self._create_snap_button()
        self.iface.pluginToolBar().addWidget(self._snap_btn)

        # will be set False in run()
        self.first_start = True

        QgsProject.instance().readProject.connect(restore_no_legend_layers)


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&ParcelPro'),
                action)
            self.iface.removeToolBarIcon(action)

        # Remove snap dropdown button
        with contextlib.suppress(Exception):
            self._snap_btn.deleteLater()

        with contextlib.suppress(Exception):
            QgsProject.instance().readProject.disconnect(restore_no_legend_layers)

        # Remove all tools
        self.destroyAllTools()


    def run(self):
        """Run method that performs all the real work"""
        if self.active:
            # Plugin is already active → deactivate
            self.destroyAllTools()  # deactivate map tools
            self.active = False
            return  # Exit early
        
        # If we get here → plugin is inactive → activate it
        self.active = True
        
        # 🔥 remove old dock if it already exists (important for reloads)
        if hasattr(self, "terminal_dock") and self.terminal_dock:
            self.destroyAllTools()
            self.terminal_dock = None

        