# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UgsurvDialog
                                 A QGIS plugin
 General purpose CAD like plugin for Ug survey works
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-20
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Nuwe Surv
        email                : nuwesurv@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


import os

from PyQt5.QtCore import Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QDockWidget,
    QWidget,
    QGroupBox,
    QVBoxLayout,
    QLabel,
    QPushButton,
    QHBoxLayout,
    QSpacerItem,
    QSizePolicy,
    QProgressBar,
    QTabWidget,
)
from qgis.gui import QgsMapLayerComboBox
from PyQt5.QtWidgets import QLineEdit


class UgsurvDialog(QDockWidget):
    def __init__(self, parent=None):
        super().__init__("Parcel_Pro", parent)

        icon_path = os.path.join(os.path.dirname(__file__), "icon.png")
        self.setWindowIcon(QIcon(icon_path))

        # Allow docking areas
        self.setAllowedAreas(
            Qt.LeftDockWidgetArea |
            Qt.RightDockWidgetArea |
            Qt.BottomDockWidgetArea
        )

        # 🔥 REQUIRED: Dock widgets need a container
        container = QWidget()
        self.setWidget(container)
        # self.setMaximumHeight(150)
        self.setMaximumWidth(600)

        # =========================
        # Main layout
        # =========================
        self.MainLayout = QVBoxLayout(container)

        self.TabLayout = QTabWidget()
        self.MainLayout.addWidget(self.TabLayout)

        # =========================
        # TAB 1
        # =========================
        self.tab1 = QGroupBox()
        self.tab1_layout = QVBoxLayout()

        inputheight = 25

        # Select geopackage
        geoSelectHori = QHBoxLayout()

        self.geoSelectLabel = QLabel('Select layer of interest:')
        self.geoSelectLabel.setFixedWidth(120)

        self.maplayerSelector = QgsMapLayerComboBox()
        self.maplayerSelector.setFixedHeight(inputheight)

        geoSelectHori.addWidget(self.geoSelectLabel)
        geoSelectHori.addWidget(self.maplayerSelector)
        self.tab1_layout.addLayout(geoSelectHori)

        

        # Prompt the user to select two parcels
        geoSelectHori3 = QHBoxLayout()
        self.geoSelectLabel3 = QLabel('Threshold:')
        self.geoSelectLabel3.setFixedWidth(120)
        
        hspacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        
        self.tolerance = QLineEdit()
        self.tolerance.setFixedWidth(120)  # set width to 120 pixels
        self.tolerance.setPlaceholderText("Enter tolerance") 
        self.tolerance.setText('0.2m')
        
        geoSelectHori3.addWidget(self.geoSelectLabel3)
        geoSelectHori3.addItem(hspacer)
        geoSelectHori3.addWidget(self.tolerance)
        self.tab1_layout.addLayout(geoSelectHori3)
        
        
        
        # Spacer
        self.tab1_layout.addItem(
            QSpacerItem(0, 10, QSizePolicy.Minimum, QSizePolicy.Expanding)
        )

        self.resultLabel1 = QLabel('Result:')
        self.tab1_layout.addWidget(self.resultLabel1)


        # Buttons + progress
        buttongrouper1 = QHBoxLayout()

        self.progressBar1 = QProgressBar()
        self.closebutton1 = QPushButton('Close')
        self.fixtopology = QPushButton('Fix topology')

        buttongrouper1.addWidget(self.progressBar1)
        buttongrouper1.addWidget(self.fixtopology)

        self.tab1_layout.addLayout(buttongrouper1)

        self.tab1.setLayout(self.tab1_layout)
        self.TabLayout.addTab(self.tab1, 'Fix Topology')
