# -*- coding: utf-8 -*-
"""
/***************************************************************************
 parcelplotterDialog
                                 A QGIS plugin
 Plotting polygons based on ordered codes.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-10
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Nuwe Surv
        email                : nuwesurv@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtWidgets import (
    QDockWidget, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QPushButton
)

from qgis.gui import QgsMapLayerComboBox
from qgis.core import (
    QgsFeature,
    QgsCoordinateTransform,
    QgsProject,
    QgsSpatialIndex,
)


class GeometryAppenderDock(QDockWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle('Append Selected Parcels')

        inputheight = 25

        root = QWidget()
        layout = QVBoxLayout(root)
        layout.setSpacing(6)
        layout.setContentsMargins(8, 8, 8, 8)

        # Source layer selector
        from_row = QHBoxLayout()
        from_row.addWidget(QLabel('Copy selected from:'))
        self.from_combo = QgsMapLayerComboBox()
        self.from_combo.setFixedHeight(inputheight)
        from_row.addWidget(self.from_combo)
        layout.addLayout(from_row)

        # Target layer selector
        to_row = QHBoxLayout()
        to_row.addWidget(QLabel('Add selected to:'))
        self.to_combo = QgsMapLayerComboBox()
        self.to_combo.setFixedHeight(inputheight)
        to_row.addWidget(self.to_combo)
        layout.addLayout(to_row)

        # Status label
        self.response = QLabel('No layer selected currently.')
        layout.addWidget(self.response)

        layout.addStretch()

        # Append button
        btn_row = QHBoxLayout()
        btn_row.addStretch()
        self.append_btn = QPushButton('Append')
        btn_row.addWidget(self.append_btn)
        layout.addLayout(btn_row)

        self.setWidget(root)
        self.append_btn.clicked.connect(self.append_parcels)

    def _set_status(self, message, color="green"):
        self.response.setStyleSheet(f"color: {color};")
        self.response.setText(message)

    def append_parcels(self):
        from_layer = self.from_combo.currentLayer()
        if not from_layer:
            self._set_status("No 'from' layer selected!", "red")
            return

        to_layer = self.to_combo.currentLayer()
        if not to_layer:
            self._set_status("No 'to' layer selected!", "red")
            return

        selected_features = from_layer.selectedFeatures()
        if not selected_features:
            self._set_status("No features selected in 'From' layer!", "red")
            return

        # Build spatial index for target layer
        index = QgsSpatialIndex(to_layer.getFeatures())
        existing_geoms = {f.id(): f.geometry() for f in to_layer.getFeatures()}

        try:
            if not to_layer.isEditable():
                to_layer.startEditing()

            to_fields = to_layer.fields()
            new_features = []

            transform = None
            if from_layer.crs() != to_layer.crs():
                transform = QgsCoordinateTransform(
                    from_layer.crs(), to_layer.crs(), QgsProject.instance()
                )

            for feat in selected_features:
                geom = feat.geometry()

                if transform:
                    geom.transform(transform)

                if not geom.isGeosValid():
                    geom = geom.makeValid()

                # Skip duplicates
                candidate_ids = index.intersects(geom.boundingBox())
                exists = False
                for cid in candidate_ids:
                    existing_geom = existing_geoms[cid]
                    if geom.equals(existing_geom):
                        exists = True
                        break
                    if geom.intersects(existing_geom):
                        overlap = geom.intersection(existing_geom).area()
                        if overlap / geom.area() > 0.95:
                            exists = True
                            break

                if exists:
                    self._set_status("A selected feature already exists in the target layer.", "orange")
                    continue

                new_feat = QgsFeature(to_fields)
                new_feat.setGeometry(geom)

                attrs = []
                for field in to_fields:
                    if field.name().lower() == 'fid':
                        attrs.append(None)
                    elif field.name() in feat.fields().names():
                        attrs.append(feat[field.name()])
                    else:
                        attrs.append(None)
                new_feat.setAttributes(attrs)
                new_features.append(new_feat)

            to_layer.addFeatures(new_features)

            self._set_status(
                f"Successfully appended {len(new_features)} feature(s).",
                "green"
            )

        except Exception as e:
            to_layer.rollBack()
            self._set_status(f"Error: {e}", "red")
