# -*- coding: utf-8 -*-
"""
/***************************************************************************
 parcelplotterDialog
                                 A QGIS plugin
 Plotting polygons based on ordered codes.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-10
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Nuwe Surv
        email                : nuwesurv@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import (
    QDockWidget, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QPushButton, QComboBox
)

from qgis.gui import QgsProjectionSelectionWidget, QgsMapLayerComboBox
from qgis.core import (
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsProject,
)


class CrsAdjustDock(QDockWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle('CRS Adjustment')

        inputheight = 25

        root = QWidget()
        layout = QVBoxLayout(root)
        layout.setSpacing(6)
        layout.setContentsMargins(8, 8, 8, 8)

        # Layer selector
        layer_row = QHBoxLayout()
        lbl_layer = QLabel('Selected features in:')
        self.layer_combo = QgsMapLayerComboBox()
        self.layer_combo.setFixedHeight(inputheight)
        layer_row.addWidget(lbl_layer)
        layer_row.addWidget(self.layer_combo)
        layout.addLayout(layer_row)

        # CRS selector
        crs_row = QHBoxLayout()
        lbl_crs = QLabel('Apply this CRS:')
        self.crs_widget = QgsProjectionSelectionWidget()
        self.crs_widget.setCrs(QgsCoordinateReferenceSystem("EPSG:32636"))
        crs_row.addWidget(lbl_crs)
        crs_row.addWidget(self.crs_widget)
        layout.addLayout(crs_row)

        # Project direction selector
        dir_row = QHBoxLayout()
        lbl_dir = QLabel('Project direction:')
        self.dir_combo = QComboBox()
        self.dir_combo.addItem('Forward  (selected CRS → layer CRS)')
        self.dir_combo.addItem('Reverse  (layer CRS → selected CRS)')
        self.dir_combo.setFixedHeight(inputheight)
        dir_row.addWidget(lbl_dir)
        dir_row.addWidget(self.dir_combo)
        layout.addLayout(dir_row)

        # Status label
        self.response = QLabel('No layer selected currently.')
        layout.addWidget(self.response)

        layout.addStretch()

        # Apply button
        btn_row = QHBoxLayout()
        btn_row.addStretch()
        self.apply_btn = QPushButton('Apply CRS')
        btn_row.addWidget(self.apply_btn)
        layout.addLayout(btn_row)

        self.setWidget(root)
        self.apply_btn.clicked.connect(self.adjust_crs)

    def _set_status(self, message, color="green"):
        self.response.setStyleSheet(f"color: {color};")
        self.response.setText(message)

    def adjust_crs(self):
        from_layer = self.layer_combo.currentLayer()
        if not from_layer:
            self._set_status("No layer selected!", "red")
            return

        selected_features = from_layer.selectedFeatures()
        if not selected_features:
            self._set_status("No features selected in layer!", "red")
            return

        target_crs = self.crs_widget.crs()
        is_forward = self.dir_combo.currentIndex() == 0

        try:
            if not from_layer.isEditable():
                from_layer.startEditing()

            if is_forward:
                # Forward: interpret raw coordinates as target_crs, convert to layer CRS
                transform = QgsCoordinateTransform(
                    target_crs, from_layer.crs(), QgsProject.instance()
                )
            else:
                # Reverse: interpret raw coordinates as layer CRS, convert to target_crs
                transform = QgsCoordinateTransform(
                    from_layer.crs(), target_crs, QgsProject.instance()
                )

            for feat in selected_features:
                geom = feat.geometry()
                geom.transform(transform)
                if not geom.isGeosValid():
                    geom = geom.makeValid()
                from_layer.changeGeometry(feat.id(), geom)

            direction = "forward" if is_forward else "reverse"
            epsg = target_crs.postgisSrid()
            self._set_status(
                f"Adjusted {len(selected_features)} feature(s) [{direction}] → EPSG:{epsg}.",
                "green"
            )

        except Exception as e:
            from_layer.rollBack()
            self._set_status(f"Error: {e}", "red")
