# -*- coding: utf-8 -*-
"""
/***************************************************************************
 parcelplotterDialog
                                 A QGIS plugin
 Plotting polygons based on ordered codes.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-10
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Nuwe Surv
        email                : nuwesurv@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5.QtCore import Qt
import qgis
from qgis.PyQt.QtWidgets import QGroupBox, QDialog, QVBoxLayout, QLabel, QFileDialog, QTableWidget, QPushButton, QTableWidgetItem, QHBoxLayout, QSpacerItem, QSizePolicy, QComboBox, QGridLayout
import os.path
# import pandas as pd
# import geopandas as gpd
# import shapely as sh
from qgis.gui import QgsProjectionSelectionWidget, QgsMapLayerComboBox
from qgis.core import QgsCoordinateReferenceSystem
from qgis.core import (
    QgsFeature,
    QgsCoordinateTransform,
    QgsProject,
    QgsWkbTypes,
    QgsGeometry,
    QgsVectorLayer,
    QgsField,
    QgsSpatialIndex
)



class CrsAdjustDialog(QDialog):
    def __init__(self, parent = None):
        super().__init__(parent)
        self.setWindowTitle('CRS adjustment for individual features')
        self.setMaximumWidth(400)
        self.setFixedWidth(400)
        self.inputheight = 25

        # Main Layout.
        self.templayout = QVBoxLayout()
        
        # Select geopackage layer.
        self.geoSelectHori1 = QHBoxLayout()
        self.geoSelectLabel1 = QLabel('Selected features in:')
        self.geoSelectLabel1.setFixedWidth(100)
        self.maplayerSelector1 = QgsMapLayerComboBox()
        self.maplayerSelector1.setFixedHeight(self.inputheight)
        self.geoSelectHori1.addWidget(self.geoSelectLabel1)
        self.geoSelectHori1.addWidget(self.maplayerSelector1)
        self.templayout.addLayout(self.geoSelectHori1)
        
        # Select geopackage layer.
        self.geoSelectHori2 = QHBoxLayout()
        self.geoSelectLabel2 = QLabel('Apply this CRS:')
        self.geoSelectLabel2.setFixedWidth(100)
        
        default_crs = QgsCoordinateReferenceSystem("EPSG:32636")
        self.crsWidget = QgsProjectionSelectionWidget()
        self.crsWidget.setCrs(default_crs)
        
        self.geoSelectHori2.addWidget(self.geoSelectLabel2)
        self.geoSelectHori2.addWidget(self.crsWidget)
        self.templayout.addLayout(self.geoSelectHori2)

        # Response
        self.filepath_store = QLabel("")
        self.response = QLabel("No layer selected currently!")
        self.templayout.addWidget(self.response)



        # Add the close and run buttons.
        self.buttongrouper = QHBoxLayout()
        self.hspacer = QSpacerItem(40, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.applybutton = QPushButton('Apply CRS')
        self.applybutton.setFixedWidth(100)

        self.buttongrouper.addItem(self.hspacer)
        self.buttongrouper.addWidget(self.applybutton)
        self.buttongrouper.setSpacing(10)
        self.templayout.addItem(self.buttongrouper)

        self.setLayout(self.templayout)
        self.applybutton.clicked.connect(self.adjust_crs)

    def update_result_label(self, label, message, color="green"):
        label.setStyleSheet(f"color: {color};")
        label.setText(f"Result: {message}")

    
    
    def adjust_crs(self):
        from_layer = self.maplayerSelector1.currentLayer()
        if not from_layer:
            self.update_result_label(self.response, "No layer selected!", "red")
            return
        
        # Check selection
        selected_features = from_layer.selectedFeatures()
        if not selected_features:
            self.update_result_label(self.response, "No features selected in layer!", "red")
            return
        
        # Espg selector
        to_epsg_code = self.crsWidget.crs().postgisSrid() 

        try:
            # Start editing target layer if not already
            if not from_layer.isEditable():
                from_layer.startEditing()
            
            # Prepare CRS transform
            target_crs = self.crsWidget.crs()
            transform = QgsCoordinateTransform(
                target_crs,
                from_layer.crs(),
                QgsProject.instance()
                )

            for feat in selected_features:
                geom = feat.geometry()
                geom.transform(transform)

                if not geom.isGeosValid():
                    geom = geom.makeValid()

                from_layer.changeGeometry(
                    feat.id(),
                    geom
                    )

            # # Commit changes
            # from_layer.commitChanges()

            self.update_result_label(
                self.response,
                f"Successfully adjusted {len(selected_features)} feature(s) to crs: {to_epsg_code}.",
                "green"
            )

        except Exception as e:
            from_layer.rollBack()
            self.update_result_label(self.response, f"Error: {str(e)}", "red")