# -*- coding: utf-8 -*-
"""
/***************************************************************************
 parcelplotterDialog
                                 A QGIS plugin
 Plotting polygons based on ordered codes.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-10
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Nuwe Surv
        email                : nuwesurv@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt.QtGui import QPixmap, QFont
from PyQt5.QtCore import Qt
import qgis
from qgis.PyQt.QtWidgets import (
                            QGroupBox, 
                            QDialog, 
                            QVBoxLayout, 
                            QLabel, 
                            QFileDialog, 
                            QTableWidget, 
                            QPushButton, 
                            QTableWidgetItem, 
                            QHBoxLayout, 
                            QSpacerItem, 
                            QSizePolicy, 
                            QComboBox, 
                            QGridLayout,
                            QGraphicsView,
                            QGraphicsScene,
                            QTextEdit, 
                            QLineEdit,
                            QGraphicsProxyWidget
                        )
from qgis.core import QgsProject, QgsVectorLayer, QgsField, QgsRasterLayer

import math
from osgeo import gdal, osr
from qgis.gui import QgsProjectionSelectionWidget
from qgis.core import QgsCoordinateReferenceSystem
from PyQt5.QtCore import Qt, pyqtSignal
from PyQt5.QtWidgets import QWidget, QHBoxLayout, QPushButton, QTextEdit
from PyQt5.QtGui import QFont, QIcon, QPainter, QColor
from PyQt5.QtCore import QSize

import fitz
import tempfile
from PIL import Image
import base64
from io import BytesIO







class ZoomableView(QGraphicsView):
    # 👇 custom signal (emit x, y)
    clicked = pyqtSignal(float, float)
    
    def __init__(self, parent=None):
        super().__init__(parent)

        self.setCursor(Qt.CrossCursor) # set the cursor to become a cross
        self.setTransformationAnchor(QGraphicsView.AnchorUnderMouse)
        self.setResizeAnchor(QGraphicsView.AnchorUnderMouse)
        self.setDragMode(QGraphicsView.ScrollHandDrag)

    def wheelEvent(self, event):
        zoomFactor = 1.25

        if event.angleDelta().y() > 0:
            self.scale(zoomFactor, zoomFactor)
        else:
            self.scale(1 / zoomFactor, 1 / zoomFactor)
            
    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            # Convert mouse pos to scene coords
            scene_pos = self.mapToScene(event.pos())

            # Check if click is on a QGraphicsProxyWidget
            item = self.scene().itemAt(scene_pos, self.transform())
            if item is not None and isinstance(item, QGraphicsProxyWidget):
                # Clicked on a widget → ignore view click
                super().mousePressEvent(event)
                return  # don't emit clicked signal

            # Otherwise emit signal
            self.clicked.emit(scene_pos.x(), scene_pos.y())

        super().mousePressEvent(event)









class ImportPrintDialog(QDialog):
    def __init__(self, terminal_dock=None, parent = None):
        super().__init__(parent)
        self.setWindowTitle('Import Print')
        self.setMinimumWidth(1000)
        self.setMinimumHeight(700)
        # self.setFixedWidth(400)
        self.terminal_dock = terminal_dock
        self.align_points = []   # store active alignment points

        # Main Layout.
        self.templayout = QVBoxLayout()
        
        # Pdf tools setup
        self.image_holder = {}
        self.choosen_pagenumber = 0


        # FilePicking Button.
        self.filepicker = QPushButton('Select print file:')
        self.filepicker.clicked.connect(self.fileselector)
        self.templayout.addWidget(self.filepicker)

        # Cordinate system Button.
        default_crs = QgsCoordinateReferenceSystem("EPSG:32636")
        self.crsWidget = QgsProjectionSelectionWidget()
        self.crsWidget.setCrs(default_crs)
        self.templayout.addWidget(self.crsWidget)

        # Response
        self.filepath_store = QLabel("")
        self.response = QLabel("No file Path selected currently!")
        self.templayout.addWidget(self.response)
        
        # ---- ZOOMABLE IMAGE VIEW ----
        self.view = ZoomableView()
        self.scene = QGraphicsScene(self)

        self.view.setScene(self.scene)

        # self.pixmap = QPixmap(r"C:\Users\Nuwe Surv\Desktop\progs\grid_detect\image.png")
        # self.pixmap_item = self.scene.addPixmap(self.pixmap)
        # self.pixmap_item.setCursor(Qt.CrossCursor)
        self.view.clicked.connect(self.add_align_point)

        self.templayout.addWidget(self.view)


        # Add the next and prev pages.
        self.buttongrouper1 = QHBoxLayout()
        self.hspacer1 = QSpacerItem(40, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.hspacer2 = QSpacerItem(40, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.prevbutton = QPushButton('<< Prev')
        self.prevbutton.setFixedWidth(100)
        
        self.choosen_pagenumber_label = QLabel(f"{self.choosen_pagenumber}")
        
        self.nextbutton = QPushButton('Next >>')
        self.nextbutton.setFixedWidth(100)

        self.buttongrouper1.addItem(self.hspacer1)
        self.buttongrouper1.addWidget(self.prevbutton)
        self.buttongrouper1.addWidget(self.choosen_pagenumber_label)
        self.buttongrouper1.addWidget(self.nextbutton)
        self.buttongrouper1.addItem(self.hspacer2)
        self.buttongrouper1.setSpacing(10)
        self.templayout.addLayout(self.buttongrouper1)
        self.prevbutton.clicked.connect(self.prevpage)
        self.nextbutton.clicked.connect(self.nextpage)


        # Add the close and run buttons.
        self.buttongrouper2 = QHBoxLayout()
        self.hspacer3 = QSpacerItem(40, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.plotbutton = QPushButton('Align print')
        self.plotbutton.setFixedWidth(100)

        self.buttongrouper2.addItem(self.hspacer3)
        self.buttongrouper2.addWidget(self.plotbutton)
        self.buttongrouper2.setSpacing(10)
        self.templayout.addLayout(self.buttongrouper2)

        self.setLayout(self.templayout)
        self.plotbutton.clicked.connect(self.align_raster)


    def nextpage(self):
        if self.choosen_pagenumber < len(self.image_holder) - 1:
            self.choosen_pagenumber += 1
            self.updatePageView()

    def prevpage(self):
        if self.choosen_pagenumber > 0:
            self.choosen_pagenumber -= 1
            self.updatePageView()
        
    def updatePageView(self):
        self.scene.clear()
        self.align_points.clear()

        self.pixmap = QPixmap(self.image_holder[self.choosen_pagenumber])
        self.pixmap_item = self.scene.addPixmap(self.pixmap)
        self.pixmap_item.setCursor(Qt.CrossCursor)

        # ✅ update label
        total = len(self.image_holder)
        self.choosen_pagenumber_label.setText(
            f"{self.choosen_pagenumber+1} / {total}"
        )
        
        # 👇 UX polish
        self.prevbutton.setEnabled(self.choosen_pagenumber > 0)
        self.nextbutton.setEnabled(self.choosen_pagenumber < total - 1)






    # Function to read and add images to the gridview.
    def load_pdf_images(self, pdf_path):
        pdf = fitz.open(pdf_path)
        n_pages = len(pdf)
        # Create ONE temp directory for all pages
        self.temp_dir = tempfile.mkdtemp(prefix="Ugsurv_pdf_pages_")

        for page_number in range(n_pages):
            # Load the page
            page_obj = pdf[page_number]
            
            # Render page as an image (pixmap)
            pix = page_obj.get_pixmap(
                matrix=fitz.Matrix(2, 2),  # Scale factor (2x for higher resolution)
                alpha=False,  # No transparency
                annots=True  # Include annotations and form fields
            )

            # save pdf images.
            # Convert to PIL
            img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)

            # Save to temp file
            image_path = os.path.join(self.temp_dir, f"page_{page_number}.png")
            img.save(image_path, "PNG")
            self.image_holder[page_number] = image_path
            
        pdf.close()



    # ===================================================================================================
    def refresh(self):
        self.response.setText('Input been refreshed 👍')
        self.filepath_store.setText('')
        self.scene.clear()
        self.align_points = []




    # ===================================================================================================
    def fileselector(self):
        self.refresh()
        filepath, _ = QFileDialog.getOpenFileName(self, 'Select files...','',"Image Files (*.png *.jpg *.jpeg *.pdf)")
        
        if os.path.exists(filepath) :
            self.response.setText(f'File selected: {filepath} 👍')
            self.filepath_store.setText(filepath)
            
        try:
            # Read file
            if filepath.endswith('.pdf'):
                self.load_pdf_images(filepath)
                self.updatePageView()
                
            else:
                self.scene.clear()
                self.image_holder = {}
                self.image_holder = {0: filepath}
                self.choosen_pagenumber = 0
                self.updatePageView()
                
        except Exception as e:
            self.response.setText(f"Error: {str(e)}")




    def align_raster(self):
        filepath = self.filepath_store.text()

        if not os.path.exists(filepath) or filepath == "No file selected":
            self.response.setText("File does not exist")
            return

        if len(self.align_points) != 2:
            self.response.setText(
                f"Caution: Only two points are needed for 2D align but {len(self.align_points)} were selected."
            )
            return

        # --------------------------------------------------
        # Open raster FIRST (needed for height)
        # --------------------------------------------------
        ds = gdal.Open(self.image_holder[self.choosen_pagenumber])
        if ds is None:
            self.response.setText("Failed to open raster.")
            return

        width = ds.RasterXSize
        height = ds.RasterYSize

        # --------------------------------------------------
        # Get image pixel coordinates
        # --------------------------------------------------
        px1, py1 = self.align_points[0]['xy']
        px2, py2 = self.align_points[1]['xy']

        # Convert image Y (downwards) → Cartesian Y (upwards)
        py1 = height - py1
        py2 = height - py2

        # --------------------------------------------------
        # Parse GCP coordinates
        # --------------------------------------------------
        def parse_gcp(text):
            text = str(text).strip().replace(" ", "")
            if text.count(",") != 1:
                return None
            e, n = text.split(",")
            return float(e), float(n)

        gcp1 = parse_gcp(self.align_points[0]['text_edit'].text())
        gcp2 = parse_gcp(self.align_points[1]['text_edit'].text())

        if not gcp1 or not gcp2:
            self.response.setText("Incorrect coordinate format. Use 'E,N'")
            return

        x1, y1 = gcp1
        x2, y2 = gcp2

        # --------------------------------------------------
        # Compute conformal transformation
        # --------------------------------------------------
        dx_img = px2 - px1
        dy_img = py2 - py1

        dx_map = x2 - x1
        dy_map = y2 - y1

        img_dist = math.hypot(dx_img, dy_img)
        map_dist = math.hypot(dx_map, dy_map)

        if img_dist == 0:
            self.response.setText("Image points are identical.")
            return

        scale = map_dist / img_dist

        rotation = math.atan2(dy_map, dx_map) - math.atan2(dy_img, dx_img)

        cos_r = math.cos(rotation)
        sin_r = math.sin(rotation)

        # Affine parameters (proper conformal matrix)
        a = scale * cos_r
        b = -scale * sin_r
        c = scale * sin_r
        d = -scale * cos_r

        # --------------------------------------------------
        # Compute translation correctly
        # --------------------------------------------------
        x1_trans = scale * px1
        y1_trans = scale * (height - py1)

        Tx = x1 - x1_trans
        Ty = y1 + y1_trans

        # --------------------------------------------------
        # Build GDAL geotransform
        # --------------------------------------------------
        geotransform = [
            Tx,   # GT0
            a,    # GT1
            b,    # GT2
            Ty,   # GT3
            c,    # GT4
            d     # GT5
        ]

        # Optional safety check (should be positive)
        determinant = a * d - b * c
        print("Determinant:", determinant)

        # --------------------------------------------------
        # Write new raster
        # --------------------------------------------------
        output_raster = os.path.join(
            os.path.dirname(filepath),
            f"{filepath.split('/')[-1].split('.')[0]}.tif"
        )

        ds_out = gdal.Translate(output_raster, ds, format="GTiff")
        ds_out.SetGeoTransform(geotransform)

        crs = self.crsWidget.crs().postgisSrid()
        srs = osr.SpatialReference()
        srs.ImportFromEPSG(crs)
        ds_out.SetProjection(srs.ExportToWkt())

        ds_out = None
        ds = None

        # --------------------------------------------------
        # Load into QGIS
        # --------------------------------------------------
        raster_layer = QgsRasterLayer(output_raster, "Aligned Raster (2pt)")
        if not raster_layer.isValid():
            self.response.setText("Failed to create raster layer.")
            return

        QgsProject.instance().addMapLayer(raster_layer)

        self.response.setText("Raster aligned successfully (2-point conformal).")


    #     # except Exception as e:
    #     #     self.response.setText(f"Error: {str(e)}")
            
        
        
        






    def add_align_point(self, x, y):
        self.terminal_dock.commandOutputText += f'\nAlign_point: {[x, y]}'
        self.terminal_dock.commandDisplay.setText(self.terminal_dock.commandOutputText)
        
        
        self.add_textedit_at(x, y)






    def add_textedit_at(self, x, y):
        # ---- Container widget ----
        container = QWidget()
        container.setFixedHeight(60)
        layout = QHBoxLayout(container)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(5)

        # ---- QTextEdit ----
        text_edit = QLineEdit()
        # text_edit = QTextEdit()
        text_edit.setPlaceholderText("E,N")
        text_edit.setFixedSize(270, 60)

        font = QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setFamily("Arial")
        text_edit.setFont(font)

        text_edit.setStyleSheet("""
            QLineEdit {
                color: blue;
                background-color: white;
            }
        """)

        # ---- Delete Button ----
        delete_btn = QPushButton()
        delete_btn.setFixedSize(50, 60)

        # Use system trash icon
        delete_btn.setIcon(self.style().standardIcon(QPushButton().style().SP_TrashIcon))
        delete_btn.setCursor(Qt.PointingHandCursor)
        
        delete_btn.setStyleSheet("""
                QPushButton {
                    border: none;
                }
                QPushButton:hover {
                    background-color: #ffdddd;
                }
            """)

        # Add widgets to layout
        layout.addWidget(text_edit)
        layout.addWidget(delete_btn)

        # ---- Wrap in proxy ----
        proxy = QGraphicsProxyWidget()
        proxy.setWidget(container)

        self.scene.addItem(proxy)
        proxy.setPos(x, y)
        
        proxy.setFlag(proxy.ItemIsMovable, True)
        
        # 🔥 Store reference
        point_data = {
            "xy": [x,y],
            "text_edit": text_edit,
        }
        self.align_points.append(point_data)

        # ---- Delete logic ----
        def remove_widget():
            self.scene.removeItem(proxy)
            proxy.deleteLater()
            
            # remove from list
            self.align_points.remove(point_data)

        # Connect this function to the delete signal.
        delete_btn.clicked.connect(remove_widget)