# -*- coding: utf-8 -*-
"""
/***************************************************************************
 parcelplotterDialog
                                 A QGIS plugin
 Plotting polygons based on ordered codes.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-10
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Nuwe Surv
        email                : nuwesurv@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QIcon, QFont, QColor
from PyQt5.QtWidgets import (
    QDockWidget, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QTableWidget, QPushButton, QTableWidgetItem,
    QSpacerItem, QSizePolicy, QDoubleSpinBox
)

from qgis.gui import QgsMapLayerComboBox, QgsVertexMarker
from qgis.core import (
    QgsWkbTypes,
    QgsPointXY,
    QgsProject,
    QgsCoordinateTransform,
)

try:
    import numpy as np
    HAS_NUMPY = True
except ImportError:
    HAS_NUMPY = False
    print("Failed to import numpy — OverlapPointsDock requires numpy.")


class OverlapPointsDock(QDockWidget):
    """
    Dock widget that finds and highlights overlapping (duplicate or near-coincident)
    vertices within each ring of each polygon feature in a selected layer.

    Two vertices are considered overlapping when their Euclidean distance is
    strictly less than the user-supplied tolerance value (in map units).
    Both vertices of each pair are reported; clicking a row pans to and
    flashes the first vertex of that pair.
    """

    # ------------------------------------------------------------------ #
    #  Column layout                                                       #
    # ------------------------------------------------------------------ #
    COLUMNS = ["fid", "x", "y"]
    COL_FID = 0
    COL_X   = 1
    COL_Y   = 2

    FLASH_DURATION_MS = 1500

    def __init__(self, canvas, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Find Overlapping Points")
        self.canvas = canvas

        self._active_marker = None

        # ── Build UI ──────────────────────────────────────────────────── #
        root = QWidget()
        layout = QVBoxLayout(root)
        layout.setSpacing(6)
        layout.setContentsMargins(8, 8, 8, 8)

        # Layer selector row
        layer_row = QHBoxLayout()
        lbl_layer = QLabel("Select layer:")
        lbl_layer.setFixedWidth(100)
        self.layer_combo = QgsMapLayerComboBox()
        self.layer_combo.setFixedHeight(26)
        layer_row.addWidget(lbl_layer)
        layer_row.addWidget(self.layer_combo)
        layout.addLayout(layer_row)

        # Tolerance row
        tol_row = QHBoxLayout()
        lbl_tol = QLabel("Tolerance (m):")
        lbl_tol.setFixedWidth(100)
        self.tol_spin = QDoubleSpinBox()
        self.tol_spin.setRange(0.0001, 100.0)
        self.tol_spin.setValue(0.001)
        self.tol_spin.setDecimals(4)
        self.tol_spin.setSingleStep(0.001)
        self.tol_spin.setToolTip(
            "Vertex pairs whose distance is BELOW this value are reported as overlapping."
        )
        self.tol_spin.setFixedHeight(26)
        tol_row.addWidget(lbl_tol)
        tol_row.addWidget(self.tol_spin)
        tol_row.addStretch()
        layout.addLayout(tol_row)

        # Result table
        self.table = QTableWidget()
        self.table.setColumnCount(len(self.COLUMNS))
        self.table.setHorizontalHeaderLabels(self.COLUMNS)
        self.table.setRowCount(0)
        self.table.setEditTriggers(QTableWidget.NoEditTriggers)
        self.table.setSelectionBehavior(QTableWidget.SelectRows)
        self.table.setAlternatingRowColors(True)
        self.table.setColumnWidth(self.COL_FID, 55)
        self.table.setColumnWidth(self.COL_X,   95)
        self.table.setColumnWidth(self.COL_Y,   95)
        self.table.cellClicked.connect(self._on_row_clicked)
        layout.addWidget(self.table)

        # Status label
        self.status_label = QLabel("No search run yet.")
        layout.addWidget(self.status_label)

        # Button row
        btn_row = QHBoxLayout()
        btn_row.addStretch()
        self.run_btn = QPushButton("Find Overlaps")
        self.run_btn.setFixedWidth(120)
        self.run_btn.clicked.connect(self.run_search)
        btn_row.addWidget(self.run_btn)
        layout.addLayout(btn_row)

        self.setWidget(root)

    # ------------------------------------------------------------------ #
    #  UI helpers                                                          #
    # ------------------------------------------------------------------ #

    def _set_status(self, message, color="green"):
        self.status_label.setStyleSheet(f"color: {color};")
        self.status_label.setText(message)

    def _clear_table(self):
        self.table.setRowCount(0)

    def _append_row(self, feat_id, x, y):
        row = self.table.rowCount()
        self.table.insertRow(row)
        values = [str(feat_id), f"{x:.4f}", f"{y:.4f}"]
        for col, val in enumerate(values):
            item = QTableWidgetItem(val)
            item.setTextAlignment(Qt.AlignCenter)
            self.table.setItem(row, col, item)

    # ------------------------------------------------------------------ #
    #  Canvas interaction                                                  #
    # ------------------------------------------------------------------ #

    def _on_row_clicked(self, row, _col):
        x_item = self.table.item(row, self.COL_X)
        y_item = self.table.item(row, self.COL_Y)
        if not (x_item and y_item):
            return

        try:
            x = float(x_item.text())
            y = float(y_item.text())
        except ValueError:
            return

        point = QgsPointXY(x, y)

        layer = self.layer_combo.currentLayer()
        if layer:
            layer_crs = layer.crs()
            canvas_crs = self.canvas.mapSettings().destinationCrs()
            if layer_crs != canvas_crs:
                transform = QgsCoordinateTransform(layer_crs, canvas_crs, QgsProject.instance())
                point = transform.transform(point)

        self.canvas.setCenter(point)
        self.canvas.refresh()
        self._flash_marker(point)

    def _flash_marker(self, point):
        self._remove_active_marker()

        marker = QgsVertexMarker(self.canvas)
        marker.setCenter(point)
        marker.setColor(QColor(220, 30, 30))
        marker.setFillColor(QColor(220, 30, 30, 80))
        marker.setIconType(QgsVertexMarker.ICON_CROSS)
        marker.setIconSize(16)
        marker.setPenWidth(3)

        self._active_marker = marker

        QTimer.singleShot(self.FLASH_DURATION_MS, self._remove_active_marker)

    def _remove_active_marker(self):
        if self._active_marker is not None:
            try:
                self.canvas.scene().removeItem(self._active_marker)
            except Exception:
                pass
            self._active_marker = None

    # ------------------------------------------------------------------ #
    #  Main search logic                                                   #
    # ------------------------------------------------------------------ #

    def run_search(self):
        """Iterate every feature → every ring → every vertex pair and collect overlaps."""
        if not HAS_NUMPY:
            self._set_status("numpy is not available — cannot run.", "red")
            return

        self._clear_table()
        self._remove_active_marker()

        layer = self.layer_combo.currentLayer()
        if not layer:
            self._set_status("No layer selected!", "red")
            return

        if layer.geometryType() != QgsWkbTypes.PolygonGeometry:
            self._set_status("Selected layer must be a polygon layer.", "red")
            return

        tolerance = self.tol_spin.value()
        total_overlaps = 0

        for feature in layer.getFeatures():
            geom = feature.geometry()
            if not geom or geom.isEmpty():
                continue

            feat_id = feature.id()

            if geom.isMultipart():
                all_polygons = geom.asMultiPolygon()
            else:
                all_polygons = [geom.asPolygon()]

            for polygon in all_polygons:
                for ring in polygon:
                    if not ring or len(ring) < 3:
                        continue

                    coords = [(pt.x(), pt.y()) for pt in ring]
                    pairs = self._find_overlaps(coords, tolerance)

                    for pair in pairs:
                        self._append_row(feat_id, pair["x"], pair["y"])
                        total_overlaps += 1

        self._set_status(
            f"Found {total_overlaps} overlapping pair(s) "
            f"(tolerance < {tolerance} m).",
            "green" if total_overlaps == 0 else "darkorange"
        )

    # ------------------------------------------------------------------ #
    #  Geometry math                                                       #
    # ------------------------------------------------------------------ #

    @staticmethod
    def _find_overlaps(coords, tolerance):
        """
        Return a list of dicts for every pair of vertices in the ring whose
        Euclidean distance is strictly below *tolerance*.

        Parameters
        ----------
        coords    : list of (x, y) tuples — the ring's vertex sequence.
                    A closing duplicate (first == last) is stripped automatically.
        tolerance : float — distance limit in map units (exclusive upper bound).
        """
        # Remove the closing duplicate so we don't always flag index 0 vs last
        if coords[0] == coords[-1]:
            coords = coords[:-1]

        n = len(coords)
        if n < 2:
            return []

        pts = np.array(coords, dtype=np.float64)
        overlaps = []

        for i in range(n):
            for j in range(i + 1, n):
                diff = pts[i] - pts[j]
                dist = np.sqrt(diff[0] ** 2 + diff[1] ** 2)
                if dist < tolerance:
                    overlaps.append({
                        "vtx_a": i,
                        "vtx_b": j,
                        "x": round(coords[i][0], 4),
                        "y": round(coords[i][1], 4),
                        "dist": round(float(dist), 6),
                    })

        return overlaps
