# -*- coding: utf-8 -*-
"""
/***************************************************************************
 parcelplotterDialog
                                 A QGIS plugin
 Plotting polygons based on ordered codes.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-10
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Nuwe Surv
        email                : nuwesurv@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QIcon, QFont, QColor
from PyQt5.QtWidgets import (
    QDockWidget, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QTableWidget, QPushButton, QTableWidgetItem,
    QSpacerItem, QSizePolicy, QDoubleSpinBox
)

from qgis.gui import QgsMapLayerComboBox, QgsVertexMarker
from qgis.core import (
    QgsWkbTypes,
    QgsPointXY,
    QgsProject,
    QgsCoordinateTransform,
    QgsGeometry,
)

try:
    import numpy as np
    HAS_NUMPY = True
except ImportError:
    HAS_NUMPY = False
    print("Failed to import numpy — OverlapPointsDock requires numpy.")


class OverlapPointsDock(QDockWidget):
    """
    Dock widget that finds and highlights overlapping (duplicate or near-coincident)
    vertices within each ring of each polygon feature in a selected layer.

    Two vertices are considered overlapping when their Euclidean distance is
    strictly less than the user-supplied tolerance value (in map units).
    Both vertices of each pair are reported; clicking a row pans to and
    flashes the first vertex of that pair.
    """

    # ------------------------------------------------------------------ #
    #  Column layout                                                       #
    # ------------------------------------------------------------------ #
    COLUMNS = ["fid", "x", "y"]
    COL_FID = 0
    COL_X   = 1
    COL_Y   = 2

    FLASH_DURATION_MS = 1500

    def __init__(self, canvas, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Find Overlapping Points")
        self.canvas = canvas

        self._active_marker = None

        # ── Build UI ──────────────────────────────────────────────────── #
        root = QWidget()
        layout = QVBoxLayout(root)
        layout.setSpacing(6)
        layout.setContentsMargins(8, 8, 8, 8)

        # Layer selector row
        layer_row = QHBoxLayout()
        lbl_layer = QLabel("Select layer:")
        lbl_layer.setFixedWidth(100)
        self.layer_combo = QgsMapLayerComboBox()
        self.layer_combo.setFixedHeight(26)
        layer_row.addWidget(lbl_layer)
        layer_row.addWidget(self.layer_combo)
        layout.addLayout(layer_row)

        # Tolerance row
        tol_row = QHBoxLayout()
        lbl_tol = QLabel("Tolerance (m):")
        lbl_tol.setFixedWidth(100)
        self.tol_spin = QDoubleSpinBox()
        self.tol_spin.setRange(0.0001, 100.0)
        self.tol_spin.setValue(0.001)
        self.tol_spin.setDecimals(4)
        self.tol_spin.setSingleStep(0.001)
        self.tol_spin.setToolTip(
            "Vertex pairs whose distance is BELOW this value are reported as overlapping."
        )
        self.tol_spin.setFixedHeight(26)
        tol_row.addWidget(lbl_tol)
        tol_row.addWidget(self.tol_spin)
        tol_row.addStretch()
        layout.addLayout(tol_row)

        # Result table
        self.table = QTableWidget()
        self.table.setColumnCount(len(self.COLUMNS))
        self.table.setHorizontalHeaderLabels(self.COLUMNS)
        self.table.setRowCount(0)
        self.table.setEditTriggers(QTableWidget.NoEditTriggers)
        self.table.setSelectionBehavior(QTableWidget.SelectRows)
        self.table.setAlternatingRowColors(True)
        self.table.setColumnWidth(self.COL_FID, 55)
        self.table.setColumnWidth(self.COL_X,   95)
        self.table.setColumnWidth(self.COL_Y,   95)
        self.table.cellClicked.connect(self._on_row_clicked)
        layout.addWidget(self.table)

        # Status label
        self.status_label = QLabel("No search run yet.")
        layout.addWidget(self.status_label)

        # Button row – find
        btn_row = QHBoxLayout()
        btn_row.addStretch()
        self.run_btn = QPushButton("Find Overlaps")
        self.run_btn.setFixedWidth(120)
        self.run_btn.clicked.connect(self.run_search)
        btn_row.addWidget(self.run_btn)
        layout.addLayout(btn_row)

        # Button row – solve
        solve_row = QHBoxLayout()
        self.solve_selected_btn = QPushButton("Solve Selected")
        self.solve_selected_btn.setFixedWidth(120)
        self.solve_selected_btn.clicked.connect(self.solve_selected)
        self.solve_all_btn = QPushButton("Solve All")
        self.solve_all_btn.setFixedWidth(120)
        self.solve_all_btn.clicked.connect(self.solve_all)
        solve_row.addWidget(self.solve_selected_btn)
        solve_row.addStretch()
        solve_row.addWidget(self.solve_all_btn)
        layout.addLayout(solve_row)

        self.setWidget(root)

    # ------------------------------------------------------------------ #
    #  UI helpers                                                          #
    # ------------------------------------------------------------------ #

    def _set_status(self, message, color="green"):
        self.status_label.setStyleSheet(f"color: {color};")
        self.status_label.setText(message)

    def _clear_table(self):
        self.table.setRowCount(0)

    def _append_row(self, feat_id, x, y, meta=None):
        row = self.table.rowCount()
        self.table.insertRow(row)
        values = [str(feat_id), f"{x:.4f}", f"{y:.4f}"]
        for col, val in enumerate(values):
            item = QTableWidgetItem(val)
            item.setTextAlignment(Qt.AlignCenter)
            if col == self.COL_FID and meta is not None:
                item.setData(Qt.UserRole, meta)
            self.table.setItem(row, col, item)

    # ------------------------------------------------------------------ #
    #  Canvas interaction                                                  #
    # ------------------------------------------------------------------ #

    def _on_row_clicked(self, row, _col):
        x_item = self.table.item(row, self.COL_X)
        y_item = self.table.item(row, self.COL_Y)
        if not (x_item and y_item):
            return

        try:
            x = float(x_item.text())
            y = float(y_item.text())
        except ValueError:
            return

        point = QgsPointXY(x, y)

        layer = self.layer_combo.currentLayer()
        if layer:
            layer_crs = layer.crs()
            canvas_crs = self.canvas.mapSettings().destinationCrs()
            if layer_crs != canvas_crs:
                transform = QgsCoordinateTransform(layer_crs, canvas_crs, QgsProject.instance())
                point = transform.transform(point)

        self.canvas.setCenter(point)
        self.canvas.refresh()
        self._flash_marker(point)

    def _flash_marker(self, point):
        self._remove_active_marker()

        marker = QgsVertexMarker(self.canvas)
        marker.setCenter(point)
        marker.setColor(QColor(220, 30, 30))
        marker.setFillColor(QColor(220, 30, 30, 80))
        marker.setIconType(QgsVertexMarker.ICON_CROSS)
        marker.setIconSize(16)
        marker.setPenWidth(3)

        self._active_marker = marker

        QTimer.singleShot(self.FLASH_DURATION_MS, self._remove_active_marker)

    def _remove_active_marker(self):
        if self._active_marker is not None:
            try:
                self.canvas.scene().removeItem(self._active_marker)
            except Exception:
                pass
            self._active_marker = None

    # ------------------------------------------------------------------ #
    #  Main search logic                                                   #
    # ------------------------------------------------------------------ #

    def run_search(self):
        """Iterate every feature → every ring → every vertex pair and collect overlaps."""
        if not HAS_NUMPY:
            self._set_status("numpy is not available — cannot run.", "red")
            return

        self._clear_table()
        self._remove_active_marker()

        layer = self.layer_combo.currentLayer()
        if not layer:
            self._set_status("No layer selected!", "red")
            return

        if layer.geometryType() != QgsWkbTypes.PolygonGeometry:
            self._set_status("Selected layer must be a polygon layer.", "red")
            return

        tolerance = self.tol_spin.value()
        total_overlaps = 0

        for feature in layer.getFeatures():
            geom = feature.geometry()
            if not geom or geom.isEmpty():
                continue

            feat_id = feature.id()
            was_multipart = geom.isMultipart()

            if was_multipart:
                all_polygons = geom.asMultiPolygon()
            else:
                all_polygons = [geom.asPolygon()]

            for poly_idx, polygon in enumerate(all_polygons):
                for ring_idx, ring in enumerate(polygon):
                    if not ring or len(ring) < 3:
                        continue

                    coords = [(pt.x(), pt.y()) for pt in ring]
                    clusters = self._find_clusters(coords, tolerance)

                    for cluster in clusters:
                        avg_x = float(np.mean([coords[i][0] for i in cluster]))
                        avg_y = float(np.mean([coords[i][1] for i in cluster]))
                        meta = {
                            "feat_id": feat_id,
                            "poly_idx": poly_idx,
                            "ring_idx": ring_idx,
                            "vtx_indices": cluster,
                            "was_multipart": was_multipart,
                        }
                        self._append_row(feat_id, avg_x, avg_y, meta)
                        total_overlaps += 1

        self._set_status(
            f"Found {total_overlaps} overlapping pair(s) "
            f"(tolerance < {tolerance} m).",
            "green" if total_overlaps == 0 else "darkorange"
        )

    # ------------------------------------------------------------------ #
    #  Solve logic                                                         #
    # ------------------------------------------------------------------ #

    def solve_all(self):
        """Remove the duplicate vertex for every overlap currently in the table."""
        self._solve_rows(list(range(self.table.rowCount())))

    def solve_selected(self):
        """Remove the duplicate vertex only for the selected table row(s)."""
        rows = [idx.row() for idx in self.table.selectionModel().selectedRows()]
        if not rows:
            self._set_status("Select a row first.", "red")
            return
        self._solve_rows(rows)

    def _solve_rows(self, rows):
        layer = self.layer_combo.currentLayer()
        if not layer:
            self._set_status("No layer selected!", "red")
            return
        if not rows:
            return

        from collections import defaultdict

        # Collect clusters per (feat_id, poly_idx, ring_idx)
        by_feat = defaultdict(lambda: defaultdict(list))
        feat_was_multipart = {}

        for row in rows:
            item = self.table.item(row, self.COL_FID)
            if not item:
                continue
            meta = item.data(Qt.UserRole)
            if not meta:
                continue
            fid = meta["feat_id"]
            key = (meta["poly_idx"], meta["ring_idx"])
            by_feat[fid][key].append(meta["vtx_indices"])
            feat_was_multipart[fid] = meta["was_multipart"]

        if not by_feat:
            self._set_status("No valid overlaps to solve.", "darkorange")
            return

        was_editing = layer.isEditable()
        if not was_editing:
            layer.startEditing()

        solved = 0
        for feat_id, ring_clusters in by_feat.items():
            feature = layer.getFeature(feat_id)
            geom = feature.geometry()
            was_multipart = feat_was_multipart[feat_id]

            if was_multipart:
                all_polygons = geom.asMultiPolygon()
            else:
                all_polygons = [geom.asPolygon()]

            for (poly_idx, ring_idx), cluster_list in ring_clusters.items():
                ring = list(all_polygons[poly_idx][ring_idx])

                # First pass: compute average and record what to replace / delete.
                # Do NOT modify ring yet so indices stay valid across clusters.
                replacements = {}   # index -> new QgsPointXY at average position
                to_delete = set()   # indices to remove after replacements are set

                for vtx_indices in cluster_list:
                    # Ensure the ring stays a valid polygon (min 3 unique vertices)
                    unique_remaining = (len(ring) - 1) - len(to_delete) - (len(vtx_indices) - 1)
                    if unique_remaining < 3:
                        continue

                    avg_x = sum(ring[i].x() for i in vtx_indices) / len(vtx_indices)
                    avg_y = sum(ring[i].y() for i in vtx_indices) / len(vtx_indices)
                    avg_pt = QgsPointXY(avg_x, avg_y)

                    i0 = vtx_indices[0]
                    replacements[i0] = avg_pt
                    to_delete.update(vtx_indices[1:])
                    solved += 1

                # Apply average positions
                for idx, pt in replacements.items():
                    ring[idx] = pt
                    if idx == 0:
                        ring[-1] = pt   # keep closing vertex in sync

                # Remove extra vertices from the end toward the front
                for idx in sorted(to_delete, reverse=True):
                    if idx < len(ring) - 1:    # never touch the closing vertex slot
                        del ring[idx]

                all_polygons[poly_idx][ring_idx] = ring

            if was_multipart:
                new_geom = QgsGeometry.fromMultiPolygonXY(all_polygons)
            else:
                new_geom = QgsGeometry.fromPolygonXY(all_polygons[0])

            layer.changeGeometry(feat_id, new_geom)

        if not was_editing:
            layer.commitChanges()

        self.canvas.refresh()
        self._set_status(f"Merged {solved} cluster(s) to average. Re-running search…", "green")
        self.run_search()

    # ------------------------------------------------------------------ #
    #  Geometry math                                                       #
    # ------------------------------------------------------------------ #

    @staticmethod
    def _find_clusters(coords, tolerance):
        """
        Group near-coincident vertices into clusters using union-find.

        Two vertices are linked when their Euclidean distance is strictly below
        *tolerance*.  Transitivity is handled automatically, so three vertices
        that are each within tolerance of at least one other member end up in
        the same cluster even if the first and last are farther than *tolerance*
        apart.

        Parameters
        ----------
        coords    : list of (x, y) tuples — the ring's vertex sequence.
                    A closing duplicate (first == last) is stripped automatically.
        tolerance : float — distance limit in map units (exclusive upper bound).

        Returns
        -------
        list of sorted lists of int — one entry per cluster of size >= 2.
        """
        if coords[0] == coords[-1]:
            coords = coords[:-1]

        n = len(coords)
        if n < 2:
            return []

        pts = np.array(coords, dtype=np.float64)

        parent = list(range(n))

        def find(x):
            while parent[x] != x:
                parent[x] = parent[parent[x]]
                x = parent[x]
            return x

        for i in range(n):
            for j in range(i + 1, n):
                diff = pts[i] - pts[j]
                if np.sqrt(diff[0] ** 2 + diff[1] ** 2) < tolerance:
                    ri, rj = find(i), find(j)
                    if ri != rj:
                        parent[ri] = rj

        groups = {}
        for i in range(n):
            root = find(i)
            groups.setdefault(root, []).append(i)

        return [sorted(members) for members in groups.values() if len(members) > 1]
