# -*- coding: utf-8 -*-
"""
/***************************************************************************
 parcelplotterDialog
                                 A QGIS plugin
 Plotting polygons based on ordered codes.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-10
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Nuwe Surv
        email                : nuwesurv@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt.QtCore import Qt
import os.path
from qgis.PyQt.QtWidgets import QGroupBox, QDialog, QVBoxLayout, QLabel, QFileDialog, QTableWidget, QPushButton, QTableWidgetItem, QHBoxLayout, QSpacerItem, QSizePolicy, QComboBox, QGridLayout
from qgis.core import QgsProject, QgsVectorLayer, QgsField, QgsCoordinateReferenceSystem
from qgis.gui import QgsProjectionSelectionWidget


try:
    import pandas as pd
except Exception:
    print('Failed to find pandas module')
try:
    import geopandas as gpd
except Exception:
    print('Failed to find geopandas module')
try:
    import shapely as sh
except Exception:
    print('Failed to find shapely module')

class ParcelPlotterDialog(QDialog):
    def __init__(self, parent = None):
        super().__init__(parent)
        self.setWindowTitle('Plotting Parcels')
        self.setMaximumWidth(400)
        self.setFixedWidth(400)

        # Main Layout.
        self.templayout = QVBoxLayout()

        # FilePicking Button.
        self.filepicker = QPushButton('Select csv or excel file:')
        self.filepicker.clicked.connect(self.fileselector)
        self.templayout.addWidget(self.filepicker)

        # Cordinate system Button.
        default_crs = QgsCoordinateReferenceSystem("EPSG:32636")
        self.crsWidget = QgsProjectionSelectionWidget()
        self.crsWidget.setCrs(default_crs)
        self.templayout.addWidget(self.crsWidget)

        # Response
        self.filepath_store = QLabel("")
        self.response = QLabel("No file Path selected currently!")
        self.templayout.addWidget(self.response)

        # Tableviewer
        self.tableview = QTableWidget()
        self.tableview.setRowCount(0)
        self.tableview.setColumnCount(0)
        self.templayout.addWidget(self.tableview)

        # Add N, E, Code selctors
        self.tempHorizontal1 = QHBoxLayout()
        self.label1 = QLabel('Northings:')
        self.label2 = QLabel('Eastings:')
        self.label3 = QLabel('Code:')
        self.northings = QComboBox()
        self.eastings = QComboBox()
        self.code = QComboBox()

        self.tempHorizontal1.addWidget(self.label1,alignment=Qt.AlignmentFlag.AlignRight)
        self.tempHorizontal1.addWidget(self.northings)
        self.tempHorizontal1.addWidget(self.label2,alignment=Qt.AlignmentFlag.AlignRight)
        self.tempHorizontal1.addWidget(self.eastings)
        self.tempHorizontal1.addWidget(self.label3,alignment=Qt.AlignmentFlag.AlignRight)
        self.tempHorizontal1.addWidget(self.code)
        self.tempHorizontal1.setSpacing(10)
        self.templayout.addLayout(self.tempHorizontal1)


        # Add the close and run buttons.
        self.buttongrouper = QHBoxLayout()
        self.hspacer = QSpacerItem(40, 0, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.refreshbutton = QPushButton('Refresh')
        self.refreshbutton.setFixedWidth(100)
        self.plotbutton = QPushButton('Plot')
        self.plotbutton.setFixedWidth(100)

        self.buttongrouper.addItem(self.hspacer)
        self.buttongrouper.addWidget(self.refreshbutton)
        self.buttongrouper.addWidget(self.plotbutton)
        self.buttongrouper.setSpacing(10)
        self.templayout.addItem(self.buttongrouper)

        self.setLayout(self.templayout)
        
        self.plotbutton.clicked.connect(self.plot_parcels)
        self.refreshbutton.clicked.connect(self.refresh)


    def refresh(self):
        self.tableview.setRowCount(0)
        self.tableview.setColumnCount(0)
        self.response.setText('Input been refreshed 👍')
        self.filepath_store.setText('')

    def fileselector(self):
        filepath, _ = QFileDialog.getOpenFileName(self, 'Select files...','',"CSV/Excel Files (*.csv *.xlsx)")

        if os.path.exists(filepath) :
            if filepath.endswith('.csv'):
                df = pd.read_csv(filepath)
            elif filepath.endswith('.xlsx'):
                df = pd.read_excel(filepath)
            else:
                self.response.setText('Please select an excel or a csv')
                

            columns = df.columns.to_list()

            self.tableview.setRowCount(df.shape[0])
            self.tableview.setColumnCount(df.shape[1])
            self.tableview.setHorizontalHeaderLabels(columns)

            for idx , row in df.iterrows():
                for idy, value in enumerate(row):
                    item = QTableWidgetItem(str(value))
                    self.tableview.setItem(idx, idy, item)
            
            # First remove Add items.
            self.northings.clear()
            self.eastings.clear()
            self.code.clear()
            
            # Then Add items.
            self.northings.addItems(columns)
            self.eastings.addItems(columns)
            self.code.addItems(columns)
            
            for col in columns:
                if col.lower().count('no') > 0:
                    self.northings.setCurrentText(col)
                    
                if col.lower().count('ea') > 0:
                    self.eastings.setCurrentText(col)
                    
                if col.lower().count('co') > 0 or col.lower().count('d') > 0:
                    self.code.setCurrentText(col)

            self.response.setText(f'File selected: {filepath} 👍')
            self.filepath_store.setText(filepath)
            
            
            
    def plot_parcels(self):
        """Plot parcels using user-selected columns"""
        filepath = self.filepath_store.text()
        if not os.path.exists(filepath) or filepath == "No file selected":
            self.response.setText("File does not exist")
            return
        filename = filepath.split('/')[-1]
        print(filename)

        # Get selected column names
        eastings = self.eastings.currentText()
        northings = self.northings.currentText()
        code = self.code.currentText()

        if not all([eastings, northings, code]):
            self.response.setText("Please select all columns")
            return

        try:
            # Read file
            if filepath.endswith('.csv'):
                df = pd.read_csv(filepath)
            elif filepath.endswith('.xlsx'):
                df = pd.read_excel(filepath)

            # Validate columns
            if not all(col in df.columns for col in [eastings, northings, code]):
                self.response.setText("Selected columns not found in file")
                return

            # Validate numeric columns
            if not pd.api.types.is_numeric_dtype(df[eastings]) or not pd.api.types.is_numeric_dtype(df[northings]):
                self.response.setText("Eastings and Northings must be numeric")
                return

            # Create geometry
            df['geometry'] = df.index.map(lambda i: sh.Point([df.loc[i, eastings], df.loc[i, northings]]))

            gdf = gpd.GeoDataFrame(data=df)

            unique_codes = gdf[code].unique()
            new_gdf = gpd.GeoDataFrame(columns=[code, 'geometry'])
            for i, unique_code in enumerate(unique_codes):
                gdf1 = gdf[gdf[code] == unique_code]
                parcel_boundary = []
                for point in gdf1['geometry']:
                    parcel_boundary.append([point.x, point.y])
                try:
                    new_gdf.loc[i, code] = unique_code
                    new_gdf.loc[i, 'geometry'] = sh.Polygon(parcel_boundary)
                except Exception as e:
                    self.response.setText(f"Error creating polygon for code {unique_code}: {str(e)}")
                    continue

            if new_gdf.empty:
                self.response.setText("No valid polygons created")
                return

            epsg_code = self.crsWidget.crs().postgisSrid() 
            new_gdf = new_gdf.set_crs(epsg=epsg_code)
            # new_gdf = new_gdf.set_crs(epsg=32636)
            new_layer_path = os.path.splitext(filepath)[0] + '.gpkg'
            new_gdf.to_file(new_layer_path, driver='GPKG')

            # Load layer in QGIS
            layer_name = f'{filename}'
            layer = QgsVectorLayer(new_layer_path, layer_name, 'ogr')

            if not layer.isValid():
                self.response.setText("Layer failed to load")
                return

            QgsProject.instance().addMapLayer(layer)
            self.response.setText("Parcels plotted successfully")

        except Exception as e:
            self.response.setText(f"Error: {str(e)}")



