# -*- coding: utf-8 -*-
"""
/***************************************************************************
 parcelplotterDialog
                                 A QGIS plugin
 Plotting polygons based on ordered codes.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-10
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Nuwe Surv
        email                : nuwesurv@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import contextlib
import os

from qgis.PyQt.QtCore import Qt, QTimer
from qgis.PyQt.QtGui import QIcon, QFont, QColor
from qgis.PyQt.QtWidgets import (
    QDockWidget, QWidget, QVBoxLayout, QHBoxLayout,
    QLabel, QTableWidget, QPushButton, QTableWidgetItem,
    QSpacerItem, QSizePolicy, QDoubleSpinBox
)

from qgis.gui import QgsMapLayerComboBox, QgsVertexMarker
from qgis.core import (
    QgsWkbTypes,
    QgsPointXY,
    QgsProject,
    QgsCoordinateTransform,
)

try:
    import numpy as np
    HAS_NUMPY = True
except ImportError:
    HAS_NUMPY = False
    print("Failed to import numpy — SpikyGeomsDock requires numpy.")


class SpikyGeomsDock(QDockWidget):
    """
    Dock widget that finds and highlights 'spiky' (sharp-angled) vertices
    across all rings of all polygon features in a selected layer.

    Fixes over original version
    ───────────────────────────
    • ALL vertices of EVERY ring (exterior + holes) are checked, not just
      the first ring of each feature.
    • The angle threshold is user-configurable via a spin-box (1–179 °).
    • Clicking a table row pans to the spike AND briefly flashes a red
      cross marker on the canvas (blink effect).
    • The result table is never truncated mid-way: rows are only added,
      never reduced by a trailing setRowCount().
    • Active markers are cleaned up properly before each new search.
    """

    # ------------------------------------------------------------------ #
    #  Column layout                                                       #
    # ------------------------------------------------------------------ #
    COLUMNS = ["fid", "x", "y"]
    COL_FID = 0
    COL_X   = 1
    COL_Y   = 2

    # How long (ms) the flash marker stays visible
    FLASH_DURATION_MS = 1500

    def __init__(self, canvas, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Find Spiky Geometries")
        self.canvas = canvas

        # We track any active marker so we can remove it before the next one.
        self._active_marker = None

        # ── Build UI ──────────────────────────────────────────────────── #
        root = QWidget()
        layout = QVBoxLayout(root)
        layout.setSpacing(6)
        layout.setContentsMargins(8, 8, 8, 8)

        # Layer selector row
        layer_row = QHBoxLayout()
        lbl_layer = QLabel("Select layer:")
        lbl_layer.setFixedWidth(90)
        self.layer_combo = QgsMapLayerComboBox()
        self.layer_combo.setFixedHeight(26)
        layer_row.addWidget(lbl_layer)
        layer_row.addWidget(self.layer_combo)
        layout.addLayout(layer_row)

        # Threshold row
        thresh_row = QHBoxLayout()
        lbl_thresh = QLabel("Max angle (°):")
        lbl_thresh.setFixedWidth(90)
        self.thresh_spin = QDoubleSpinBox()
        self.thresh_spin.setRange(1.0, 179.0)
        self.thresh_spin.setValue(10.0)
        self.thresh_spin.setDecimals(1)
        self.thresh_spin.setSingleStep(1.0)
        self.thresh_spin.setToolTip(
            "Vertices whose interior angle is BELOW this value are reported as spikes."
        )
        self.thresh_spin.setFixedHeight(26)
        thresh_row.addWidget(lbl_thresh)
        thresh_row.addWidget(self.thresh_spin)
        thresh_row.addStretch()
        layout.addLayout(thresh_row)

        # Result table
        self.table = QTableWidget()
        self.table.setColumnCount(len(self.COLUMNS))
        self.table.setHorizontalHeaderLabels(self.COLUMNS)
        self.table.setRowCount(0)
        self.table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        self.table.setAlternatingRowColors(True)
        self.table.setColumnWidth(self.COL_FID, 55)
        self.table.setColumnWidth(self.COL_X,   95)
        self.table.setColumnWidth(self.COL_Y,   95)
        self.table.cellClicked.connect(self._on_row_clicked)
        layout.addWidget(self.table)

        # Status label
        self.status_label = QLabel("No search run yet.")
        layout.addWidget(self.status_label)

        # Button row
        btn_row = QHBoxLayout()
        btn_row.addStretch()
        self.run_btn = QPushButton("Find Spikes")
        self.run_btn.setFixedWidth(110)
        self.run_btn.clicked.connect(self.run_search)
        btn_row.addWidget(self.run_btn)
        layout.addLayout(btn_row)

        self.setWidget(root)

    # ------------------------------------------------------------------ #
    #  UI helpers                                                          #
    # ------------------------------------------------------------------ #

    def _set_status(self, message, color="green"):
        self.status_label.setStyleSheet(f"color: {color};")
        self.status_label.setText(message)

    def _clear_table(self):
        self.table.setRowCount(0)

    def _append_row(self, feat_id, x, y):
        """Insert one spike result at the bottom of the table."""
        row = self.table.rowCount()
        self.table.insertRow(row)
        values = [str(feat_id), f"{x:.4f}", f"{y:.4f}"]
        for col, val in enumerate(values):
            item = QTableWidgetItem(val)
            item.setTextAlignment(Qt.AlignmentFlag.AlignCenter)
            self.table.setItem(row, col, item)

    # ------------------------------------------------------------------ #
    #  Canvas interaction                                                  #
    # ------------------------------------------------------------------ #

    def _on_row_clicked(self, row, _col):
        """Pan to the spike and flash a temporary marker."""
        x_item = self.table.item(row, self.COL_X)
        y_item = self.table.item(row, self.COL_Y)
        if not (x_item and y_item):
            return

        try:
            x = float(x_item.text())
            y = float(y_item.text())
        except ValueError:
            return

        point = QgsPointXY(x, y)

        layer = self.layer_combo.currentLayer()
        if layer:
            layer_crs = layer.crs()
            canvas_crs = self.canvas.mapSettings().destinationCrs()
            if layer_crs != canvas_crs:
                transform = QgsCoordinateTransform(layer_crs, canvas_crs, QgsProject.instance())
                point = transform.transform(point)

        self.canvas.setCenter(point)
        self.canvas.refresh()
        self._flash_marker(point)

    def _flash_marker(self, point):
        """Place a red cross vertex marker that auto-removes after FLASH_DURATION_MS."""
        # Remove any previously active marker first
        self._remove_active_marker()

        marker = QgsVertexMarker(self.canvas)
        marker.setCenter(point)
        marker.setColor(QColor(220, 30, 30))          # red
        marker.setFillColor(QColor(220, 30, 30, 80))  # translucent fill
        marker.setIconType(QgsVertexMarker.IconType.ICON_CROSS)
        marker.setIconSize(16)
        marker.setPenWidth(3)

        self._active_marker = marker

        # Schedule removal
        QTimer.singleShot(
            self.FLASH_DURATION_MS,
            self._remove_active_marker
        )

    def _remove_active_marker(self):
        if self._active_marker is not None:
            with contextlib.suppress(Exception):
                self.canvas.scene().removeItem(self._active_marker)
            self._active_marker = None

    # ------------------------------------------------------------------ #
    #  Main search logic                                                   #
    # ------------------------------------------------------------------ #

    def run_search(self):
        """Iterate every feature → every ring → every vertex and collect spikes."""
        if not HAS_NUMPY:
            self._set_status("numpy is not available — cannot run.", "red")
            return

        self._clear_table()
        self._remove_active_marker()

        layer = self.layer_combo.currentLayer()
        if not layer:
            self._set_status("No layer selected!", "red")
            return

        if layer.geometryType() != QgsWkbTypes.GeometryType.PolygonGeometry:
            self._set_status("Selected layer must be a polygon layer.", "red")
            return

        threshold = self.thresh_spin.value()
        total_spikes = 0

        for feature in layer.getFeatures():
            geom = feature.geometry()
            if not geom or geom.isEmpty():
                continue

            feat_id = feature.id()

            # Normalise to a list of polygons (each polygon = list of rings)
            if geom.isMultipart():
                all_polygons = geom.asMultiPolygon()
            else:
                all_polygons = [geom.asPolygon()]

            for polygon in all_polygons:
                # polygon[0] = exterior ring, polygon[1..] = holes
                for ring in polygon:
                    if not ring or len(ring) < 3:
                        continue

                    coords = [(pt.x(), pt.y()) for pt in ring]
                    spikes = self._find_spikes(coords, threshold)

                    for spike in spikes:
                        self._append_row(
                            feat_id,
                            spike["x"],
                            spike["y"],
                        )
                        total_spikes += 1

        self._set_status(
            f"Found {total_spikes} spike(s) "
            f"(threshold < {threshold}°).",
            "green" if total_spikes == 0 else "darkorange"
        )

    # ------------------------------------------------------------------ #
    #  Geometry math                                                       #
    # ------------------------------------------------------------------ #

    @staticmethod
    def _find_spikes(coords, threshold):
        """
        Return a list of dicts for every vertex whose interior angle
        (in degrees) is strictly below *threshold*.

        Parameters
        ----------
        coords    : list of (x, y) tuples — the ring's vertex sequence.
                    A closing duplicate (first == last) is handled automatically.
        threshold : float — angle limit in degrees (exclusive upper bound).
        """
        # Remove the closing duplicate so indexing wraps correctly
        if coords[0] == coords[-1]:
            coords = coords[:-1]

        n = len(coords)
        if n < 3:
            return []

        pts = np.array(coords, dtype=np.float64)
        spikes = []

        for i in range(n):
            prev_pt = pts[i - 1]          # wraps to last when i == 0
            curr_pt = pts[i]
            next_pt = pts[(i + 1) % n]

            v1 = prev_pt - curr_pt
            v2 = next_pt - curr_pt

            norm1 = np.linalg.norm(v1)
            norm2 = np.linalg.norm(v2)

            # Skip degenerate (zero-length) edges
            if norm1 == 0.0 or norm2 == 0.0:
                continue

            cos_theta = np.dot(v1, v2) / (norm1 * norm2)
            cos_theta = np.clip(cos_theta, -1.0, 1.0)
            angle = np.degrees(np.arccos(cos_theta))

            if angle < threshold:
                spikes.append({
                    "vertex_index": i,
                    "x": round(coords[i][0], 4),
                    "y": round(coords[i][1], 4),
                    "angle": round(angle, 4),
                })

        return spikes