# -*- coding: utf-8 -*-
"""
/***************************************************************************
 parcelplotterDialog
                                 A QGIS plugin
 Plotting polygons based on ordered codes.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-10
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Nuwe Surv
        email                : nuwesurv@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.utils import iface

from PyQt5.QtCore import Qt
import qgis
from PyQt5.QtWidgets import QDockWidget, QWidget, QGroupBox, QDialog, QVBoxLayout, QLabel, QFileDialog, QTableWidget, QPushButton, QTableWidgetItem, QHBoxLayout, QSpacerItem, QSizePolicy, QComboBox, QGridLayout
# from PyQt5.QtWidgets import (
#     QDockWidget, QWidget, QVBoxLayout, QHBoxLayout,
#     QTextEdit, QLabel, QLineEdit, QSpacerItem, QSizePolicy
# )
import os.path
import numpy as np
import shapely as sh
from qgis.gui import QgsProjectionSelectionWidget, QgsMapLayerComboBox, QgsRubberBand, QgsVertexMarker
from qgis.core import QgsCoordinateReferenceSystem, QgsPointXY, Qgis
from PyQt5.QtCore import QTimer
from qgis.PyQt.QtGui import QIcon, QFont, QColor
from qgis.core import (
    QgsFeature,
    QgsCoordinateTransform,
    QgsProject,
    QgsWkbTypes,
    QgsGeometry,
    QgsVectorLayer,
    QgsField,
    QgsSpatialIndex,
    QgsPointXY
)


class SpikyGeomsDock(QDockWidget):
    def __init__(self, canvas, parent = None):
        super().__init__(parent)
        self.setWindowTitle('Find spiky geometries')
        self.inputheight = 25
        widget = QWidget()
        self.canvas = canvas
        
        # Main Layout.
        self.templayout = QVBoxLayout(widget)
        
        # Select geopackage layer.
        self.geoSelectHori1 = QHBoxLayout()
        self.geoSelectLabel1 = QLabel('Select layer in:')
        self.geoSelectLabel1.setFixedWidth(100)
        self.maplayerSelector1 = QgsMapLayerComboBox()
        self.maplayerSelector1.setFixedHeight(self.inputheight)
        self.geoSelectHori1.addWidget(self.geoSelectLabel1)
        self.geoSelectHori1.addWidget(self.maplayerSelector1)
        self.templayout.addLayout(self.geoSelectHori1)
        
        # Tableviewer
        self.field_names = [ 'angle', 'x', 'y']
        self.tableview = QTableWidget()
        self.tableview.setRowCount(0)
        self.tableview.setColumnCount(3)
        self.tableview.setHorizontalHeaderLabels(self.field_names)
        self.tableview.setColumnWidth(0, 40)
        self.tableview.setColumnWidth(1, 60)
        self.tableview.setColumnWidth(2, 60)
        self.tableview.cellClicked.connect(self.row_clicked)
        self.templayout.addWidget(self.tableview)

        # Response
        self.filepath_store = QLabel("")
        self.response = QLabel("No layer selected currently!")
        self.templayout.addWidget(self.response)



        # Add the close and run buttons.
        self.buttongrouper = QHBoxLayout()
        self.hspacer = QSpacerItem(40, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.applybutton = QPushButton('Find spikes')
        self.applybutton.setFixedWidth(100)

        self.buttongrouper.addItem(self.hspacer)
        self.buttongrouper.addWidget(self.applybutton)
        self.buttongrouper.setSpacing(10)
        self.templayout.addLayout(self.buttongrouper)

        self.applybutton.clicked.connect(self.start_search)
        
        # Add the widget
        self.setWidget(widget)
        
        
        

    def update_result_label(self, label, message, color="green"):
        label.setStyleSheet(f"color: {color};")
        label.setText(f"Result: {message}")
        
    def row_clicked(self, row, column):

        # Get value from first column
        x = self.tableview.item(row, 1).text()
        y = self.tableview.item(row, 2).text()
        if x and y:
            x = float(x)
            y = float(y)
            
            self.canvas.setCenter(QgsPointXY(x, y))
            self.canvas.refresh()
            
        

        # def flash_point(canvas, x, y):
            
        #     # Create rubber band
        #     self.rubber_band = QgsRubberBand(self.canvas, QgsWkbTypes.PointGeometry)

        #     # Style the rubberband
        #     self.rubber_band.setColor(QColor(255, 0, 0))  # Red
        #     self.rubber_band.setWidth(1)
        #     self.rubber_band.setLineStyle(Qt.DashLine)

        #     point = QgsPointXY(x, y)

        #     marker = QgsVertexMarker(canvas)
        #     marker.setCenter(point)
        #     # marker.setColor(QColor(255, 0, 0))  # red
        #     marker.setIconSize(12)
        #     marker.setIconType(QgsVertexMarker.ICON_CROSS)
        #     marker.setPenWidth(3)

        #     # auto-remove after 1.5 seconds (flash effect)
        #     QTimer.singleShot(1500, marker.deleteLater)
            
    
    def start_search(self):
        search_layer = self.maplayerSelector1.currentLayer()
        if not search_layer:
            self.update_result_label(self.response, "No layer selected!", "red")
            return
        
        
        # self.field_names = [field.name() for field in search_layer.fields()]
        self.tableview.setRowCount(search_layer.featureCount())
        

        for row_idx, feature in enumerate(search_layer.getFeatures()):
            attrs = feature.attributes()
            ring = feature.geometry().asPolygon()[0]

            coords = [(pt.x(), pt.y()) for pt in ring]
            result = self.find_spikes(coords, 10)
            if result.__len__()>0:
                for corner in result:
                    # for col_idx, value in enumerate(attrs):
                    for col_idx, col_name in enumerate(self.field_names):
                        self.tableview.setItem(
                            row_idx,
                            col_idx,
                            QTableWidgetItem(str(corner[col_name]))
                        )
                    
                
    def find_spikes(self, polygon_cords, threshold):
        # Remove duplicate closing point if polygon is closed
        if polygon_cords[0] == polygon_cords[-1]:
            polygon_cords = polygon_cords[:-1]

        sharp_corners = []

        for i in range(len(polygon_cords)):
            prev_pt = np.array(polygon_cords[i - 1])
            curr_pt = np.array(polygon_cords[i])
            next_pt = np.array(polygon_cords[(i + 1) % len(polygon_cords)])

            # Vectors from current point
            v1 = prev_pt - curr_pt
            v2 = next_pt - curr_pt

            # Calculate angle
            cos_theta = np.dot(v1, v2) / (
                np.linalg.norm(v1) * np.linalg.norm(v2)
            )
            cos_theta = np.clip(cos_theta, -1.0, 1.0)

            angle = np.degrees(np.arccos(cos_theta))

            if angle < threshold:
                sharp_corners.append({
                    "vertex_index": i,
                    "coordinate": polygon_cords[i],
                    "x": round(polygon_cords[i][0], 2),
                    "y": round(polygon_cords[i][1], 2),
                    "angle": round(angle, 2)
                })
                

        return sharp_corners